theme: null
collections:
  posts:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false # Disable if no commenting system
